# Generated by Django 3.0.6 on 2020-06-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0002_auto_20200602_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
