# Generated by Django 3.0.6 on 2020-06-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0004_auto_20200607_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='tags',
            field=models.ManyToManyField(related_name='tag_snippets', to='code_snippet.Tag'),
        ),
    ]
