# Generated by Django 3.0.6 on 2020-06-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0005_auto_20200608_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='tags',
            field=models.ManyToManyField(related_name='code_snippets', to='code_snippet.Tag'),
        ),
    ]
