# Generated by Django 3.0.6 on 2020-06-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippet', '0006_auto_20200609_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
