# Generated by Django 3.0.6 on 2020-06-11 14:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('code_snippet', '0007_auto_20200611_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
